# 가상 데이터 생성 설정

generation:
  num_images: 500 # --num-images 인자로 덮어쓸 수 있음
  max_defects_per_image: 3

  augmentation:
    scale_range: [0.05, 0.2]
    rotation_range: [0, 360]
    brightness_range: [0.7, 1.3]
    contrast_range: [0.7, 1.3]

output:
  # --output-dir 인자로 덮어쓸 수 있음
  image_dir: './swin_aoi_system/dataset_root/synthetic_data/images'
  annotation_dir: './swin_aoi_system/dataset_root/synthetic_data/annotations'

source:
  # 중요: 이 경로에 실제 배경 이미지가 있어야 합니다.
  base_image_dir: './swin_aoi_system/dataset_root/real_data/ok_images'
  # 중요: 이 경로에 실제 결함 템플릿 이미지가 있어야 합니다.
  defect_template_dir: './swin_aoi_system/dataset_root/defect_templates'
